services:
  pgq-db:
    build:
      context: ./sql
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - pgq-net

  pgq-app:
    build:
      context: ./api
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: pgq-db
    ports:
      - "8000:8000"
    networks:
      - pgq-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pgq-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - pgq-net

networks:
  pgq-net:
    driver: bridge
